### ISSUE TITLE
Cannot get the branch information from the git repository

### ISSUE THREAD

**Issue by sbadakhc** [sbadakhc/buildmetadata-maven-plugin#31]
Investigate git branch warning.

Downloaded: http://repo1.maven.org/maven2/org/tmatesoft/sqljet/sqljet/1.0.4/sqljet-1.0.4.jar (727 KB at 237.8 KB/sec)
[INFO] ShortRevision tag detected. The value is '8'.
[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/buildmetadata-maven-plugin/workspace && git rev-parse --verify --short=8 HEAD
[INFO] Working directory: /var/lib/jenkins/jobs/buildmetadata-maven-plugin/workspace
[INFO] Storing buildNumber: 3f036ee5 at timestamp: 03 October 2014
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] ShortRevision tag detected. The value is '8'.
[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/buildmetadata-maven-plugin/workspace && git rev-parse --verify --short=8 HEAD
[INFO] Working directory: /var/lib/jenkins/jobs/buildmetadata-maven-plugin/workspace
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-plugin-plugin:2.7:descriptor (default-descriptor) @ buildmetadata-maven-plugin ---

**Comment by sbadakhc** [comment]
Property of Jenkins Job was incorrect.

**Comment by JAlejandro** [comment]
Excuse me, in a project I have the same problem and don't know how to solve it.

The key  is in the Name and  Refspec config in the git-plugin ?

**Comment by sbadakhc** [comment]
Hi,

Can you provide me with the back trace of your build and provide information about who your building?
